### ISSUE TITLE
index.js is not downloaded when installing "nyg" locally or globally.

### ISSUE THREAD

**Issue by BrendanNeufeld** [Jam3/nyg#13]
Really strange. The api entry point file `package.json` > 'main' > `index.js` does not get installed. I see it in the repo. Not sure why.

**Comment by BrendanNeufeld** [comment]
![image](https://cloud.githubusercontent.com/assets/2735051/16391533/9e228318-3c75-11e6-910f-13f065dc2981.png)

**Comment by BrendanNeufeld** [comment]
`index.js` not in `npmignore` either

**Comment by iranreyes** [comment]
@BrendanNeufeld I also got this error, the `index.js` is not being downloaded. This should be easily fixed, the package should be republished. @njam3 ^

**Comment by njam3** [comment]
@BrendanNeufeld Had to upgrade npm and republish. https://github.com/SamVerschueren/npm-publish-index-test
