### ISSUE TITLE
No prompts passed in causes inquirer to fail

### ISSUE THREAD

**Issue by mikkoh** [Jam3/nyg#20]
Since now you can pass in: `prompts`, `globs`, `options`.

You could essentially pass all data you'd use via `options` and completely circumvent `prompts`.

This can essentially be easily fixed by checking if prompts is `false` or then the Array length is 0.

However. I wonder if it would be worthwhile just to make it so that you just pass `options` that defines prompts and globs. eg.

```
nyg({
  prompts: prompts,
  globs: globs,
  cwd: '/customDir'
})
```

Fixing this will also make it easier to write tests for this module since you'll be able to pass in `options` that defines all the values you'd receive through `prompts`. At this point you can just check if all files exist and are in correct form.

**Comment by njam3** [comment]
@mikkoh I would like to keep both options viable. Either passing one object with all variables or multiple arguments. I'll start working on this update.
